"""add email verification columns to brands

Revision ID: c1681e410a59
Revises: 5cb718b65e7d
Create Date: 2026-03-21 12:51:34.237116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1681e410a59'
down_revision: Union[str, None] = '5cb718b65e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Only add columns that don't already exist (idempotent)
    existing = {col["name"] for col in inspector.get_columns("brands")}

    if "is_email_verified" not in existing:
        op.add_column("brands", sa.Column(
            "is_email_verified", sa.Boolean(), nullable=False, server_default="false"
        ))
    if "email_verification_code" not in existing:
        op.add_column("brands", sa.Column("email_verification_code", sa.String(), nullable=True))
    if "email_verification_expires_at" not in existing:
        op.add_column("brands", sa.Column("email_verification_expires_at", sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'email_verification_expires_at')
    op.drop_column('brands', 'email_verification_code')
    op.drop_column('brands', 'is_email_verified')
    # ### end Alembic commands ###
