"""add email verification columns to brands

Revision ID: c1681e410a59
Revises: 5cb718b65e7d
Create Date: 2026-03-21 12:51:34.237116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1681e410a59'
down_revision: Union[str, None] = '5cb718b65e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('brands', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'email_verification_expires_at')
    op.drop_column('brands', 'email_verification_code')
    op.drop_column('brands', 'is_email_verified')
    # ### end Alembic commands ###
