"""add_organizations_and_org_memberships

Revision ID: ee874709b61e
Revises: g1h2i3j4k5l6
Create Date: 2026-03-26 11:54:22.585531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee874709b61e'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add ORG_ADMIN to the userrole enum (Alembic doesn't auto-detect enum value additions)
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ORG_ADMIN'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_brands_organization_id'), 'brands', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'brands', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_index(op.f('ix_brands_organization_id'), table_name='brands')
    op.drop_column('brands', 'organization_id')
    # ### end Alembic commands ###
    # Note: PostgreSQL does not support removing enum values — ORG_ADMIN stays in the type
